sudo pip install numpy
sudo pip install pandas
sudo pip install scikit-learn
sudo pip install matplotlib
sudo pip install keras
sudo pip install statsmodels
sudo pip install nltk
sudo pip install spark-nlp
sudo pip install boto3
sudo pip install psutil